set -g @background '#2c3135'
set -g @background-alt '#373c40'
set -g @foreground '#ffffff'
set -g @selected '#bdc3ca'
set -g @active '#4c5154'
set -g @comment '#666666'

set -g @color0 '#8ecaf1'
set -g @color1 '#f4edff'
set -g @color2 '#b2c5d4'
