set -g @background '#2e3440'
set -g @foreground '#d8dee9'
set -g @selected '#5e81ac'
set -g @active '#ebcb8b'
set -g @comment '#d8dee9'

set -g @color0 '#bf616a'
set -g @color1 '#a3be8c'
set -g @color2 '#b48ead'
