# font_family JetBrainsMono Nerd Font
font_family CaskaydiaMono Nerd Font Mono
font_size 11.0
window_margin_width 4
enable_audio_bell no
copy_on_select yes
confirm_os_window_close 0
# cursor_trail 1
hide_window_decorations yes
resize_in_steps yes
window_margin_width 10

clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask

url_style        curly
open_url_with    default
detect_urls      yes
url_regex        (ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+

background_opacity 0.8

include theme.conf
