set -g @background '#303036'    # base00
set -g @selected '#b2ccd6'      # base04
set -g @active '#eeffff'        # base06
set -g @inactive '#4a4a4a'      # base03

set -g @color0 '#ffcb6b'        # base0A
set -g @color1 '#c3e88d'        # base0B
set -g @color2 '#89ddff'        # base0C
