set -g @background '#1f1f28'    # base00
set -g @selected '#c8c093'      # base04
set -g @active '#938aa9'        # base06
set -g @inactive '#727169'      # base03

set -g @color0 '#dca561'        # base0a
set -g @color1 '#98bb6c'        # base0b
set -g @color2 '#7fb4ca'        # base0c
