set -g @background '#2b303b'    # base00
set -g @selected '#a7adba'      # base04
set -g @active '#dfe1e8'        # base06
set -g @inactive '#65737e'      # base03

set -g @color0 '#ebcb8b'        # base0A
set -g @color1 '#a3be8c'        # base0B
set -g @color2 '#96b5b4'        # base0C
