set -g @background '#32302f'    # base00
set -g @selected '#bdae93'      # base04
set -g @active '#ebdbb2'        # base06
set -g @inactive '#7c6f64'      # base03

set -g @color0 '#d8a657'        # base0A
set -g @color1 '#a9b665'        # base0B
set -g @color2 '#89b482'        # base0C
