set -g @background '#303036'
set -g @background-alt '#3b3b41'
set -g @foreground '#ffffff'
set -g @selected '#c4c1cc'
set -g @active '#504f56'
set -g @comment '#666666'

set -g @color0 '#bdbdfd'
set -g @color1 '#ffebf3'
set -g @color2 '#c2c0d9'
