# frame default
set -g @background '#5c5c51'
# frame selected
set -g @selected '#444649'

set -g @active '#444649'
set -g @inactive '#5c5c51'

set -g @color0 '#5a5d61'
set -g @color1 '#afb979'
set -g @color2 '#778284'
