# frame default
set -g @background '#6e6780'
# frame selected
set -g @selected '#95a6f4'

set -g @active '#95a6f4'
set -g @inactive '#6e6780'

set -g @color0 '#ebde76'
set -g @color1 '#b1f2a7'
set -g @color2 '#b3f4f3'
