set -g @base '{{colors.background.default.hex}}'
set -g @tile '{{colors.primary.default.hex}}'
set -g @text '{{colors.on_primary.default.hex}}'
set -g @muted '{{colors.outline.default.hex}}'

set -g @color0 '{{colors.primary_container.default.hex}}'
set -g @color1 '{{colors.tertiary.default.hex}}'
set -g @color2 '{{colors.secondary_container.default.hex}}'
