set -g @background '{{colors.surface_container.default.hex}}'
set -g @background-alt '{{colors.surface_container_high.default.hex}}'
set -g @foreground '{{colors.on_surface_variant.default.hex}}'
set -g @selected '{{colors.outline_variant.default.hex}}'
set -g @active '{{colors.surface_bright.default.hex}}'
set -g @comment '{{colors.on_surface_variant.default.hex | set_lightness: 40}}'

set -g @color0 '{{colors.primary_container.default.hex}}'
set -g @color1 '{{colors.tertiary.default.hex}}'
set -g @color2 '{{colors.secondary_container.default.hex}}'
