# Base16 github-dark for Kitty
# Author: Tinted Theming (https://github.com/tinted-theming)

background #161b22
foreground #c9d1d9
selection_background #388bfd
selection_foreground #161b22

# Basic 16 colors
color0 #161b22
color1 #f85149
color2 #2ea043
color3 #bb8009
color4 #388bfd
color5 #a371f7
color6 #2A9D9A
color7 #c9d1d9
color8 #6e7681
color9 #f85149
color10 #2ea043
color11 #bb8009
color12 #388bfd
color13 #a371f7
color14 #2A9D9A
color15 #f0f6fc
