# frame default
set -g @background '#6e7681'
# frame selected
set -g @selected '#388bfd'

set -g @active '#388bfd'
set -g @inactive '#6e7681'

set -g @color0 '#bb8009'
set -g @color1 '#2ea043'
set -g @color2 '#2A9D9A'
